# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :nfs => {
	:host_name => 'nfs.lan',
        :box_name => "centos/7",
        :ip_addr => '10.0.26.41',
        :disks => {
          :sata1 => {
            :dfile => home + '/VirtualBox VMs/sata1.vdi',
            :size => 1024,
            :port => 1
          },
          :sata2 => {
            :dfile => home + '/VirtualBox VMs/sata2.vdi',
            :size => 1024,
            :port => 2
          },
          :sata3 => {
            :dfile => home + '/VirtualBox VMs/sata3.vdi',
            :size => 1024,
            :port => 3
          },
          :sata4 => {
            :dfile => home + '/VirtualBox VMs/sata4.vdi',
            :size => 1024,
            :port => 4
          }
        }
  },
  :backup => {
  :host_name => 'backup.lan',
        :box_name => "centos/7",
        :ip_addr => '10.0.26.42',
        :disks => {
          :sata5 => {
            :dfile => home + '/VirtualBox VMs/sata5.vdi',
            :size => 1024,
            :port => 1
          },
          :sata6 => {
            :dfile => home + '/VirtualBox VMs/sata6.vdi',
            :size => 1024,
            :port => 2
          }
        }
  },
  :haproxy1 => {
	:host_name => 'haproxy1.lan',
        :box_name => "centos/7",
        :ip_addr => '10.0.26.21',
	      :disks => {
	       }
  },
  :haproxy2 => {
	:host_name => 'haproxy2.lan',
        :box_name => "centos/7",
        :ip_addr => '10.0.26.22',
	      :disks => {
	       }
  },
  :web1 => {
	:host_name => 'web1.lan',
        :box_name => "centos/7",
        :ip_addr => '10.0.26.11',
	      :disks => {
	       }
  },
  :web2 => {
	:host_name => 'web2.lan',
        :box_name => "centos/7",
        :ip_addr => '10.0.26.12',
	      :disks => {
	       }
  },
  :db1 => {
	:host_name => 'db1.lan',
        :box_name => "centos/7",
        :ip_addr => '10.0.26.31',
	      :disks => {
	       }
  },
  :db2 => {
	:host_name => 'db2.lan',
        :box_name => "centos/7",
        :ip_addr => '10.0.26.32',
	      :disks => {
	       }
  },
  :db3 => {
	:host_name => 'db3.lan',
        :box_name => "centos/7",
        :ip_addr => '10.0.26.33',
	      :disks => {
	       }
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxconfig[:host_name]
#.to_s
          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
                  needsController = false
                  boxconfig[:disks].each do |dname, dconf|
                    unless File.exist?(dconf[:dfile])
                      vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                      needsController =  true
                    end
                  end

                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh
    cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL

    case boxname.to_s
    when "nfs"
      box.vm.provision "shell", run: "always", inline: <<-SHELL
        yum install -y mdadm smartmontools hdparm gdisk parted
        SHELL
        box.vm.provision "shell", path: "shell/raid10.sh"
    when "backup"
      box.vm.provision "shell", run: "always", inline: <<-SHELL
        yum install -y mdadm smartmontools hdparm gdisk parted
        echo "0 23 * * * root rsync -a /srv /backup" >> /etc/cron.d/repo-sync
        SHELL
      box.vm.provision "shell", path: "shell/raid0.sh"
    end

      end
  end
end
