FROM alpine:3.10
LABEL Maintainer="Alex Shangin alex.shangin.13@gmail.com"

# Install packages
RUN apk --no-cache add php7 php7-fpm php7-mysqli php7-json php7-openssl php7-curl \
    php7-zlib php7-xml php7-phar php7-intl php7-dom php7-xmlreader php7-ctype php7-session \
    php7-mbstring php7-gd

# Configure PHP-FPM
# COPY config/fpm-pool.conf /etc/php7/php-fpm.d/www.conf
# COPY config/php.ini /etc/php7/conf.d/zzz_custom.ini

# Let start php
CMD ["php-fpm"]
