# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.21'
  },
  :slave => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.22'
  },
  :barman => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.23'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
          end

          box.vm.provision :"shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            setenforce 0
          SHELL

      end

  end
#  config.vm.provision "ansible" do |ansible|
#  ansible.verbose = "vvv"
#  ansible.playbook = "playbook.yml"
#  ansible.become = "true"
#  end

end
