FROM alpine:3.10
LABEL Maintainer="Alex Shangin alex.shangin.13@gmail.com"

RUN apk --no-cache add nginx bash

# Setup document root
# RUN mkdir -p /var/www/html
# Make the document root a volume
# VOLUME /var/www/html
# Add application
# WORKDIR /var/www/html
# COPY --chown=nobody src/ /var/www/html/

#RUN groupadd nginx && \
#    useradd --no-create-home nginx -g nginx

#RUN addgroup -S nginx
#RUN adduser -S nginx -G nginx

RUN rm /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
