# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant",type:"virtualbox"
  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
  end
  
  config.vm.provision "shell", inline: <<-SHELL
  mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
	
   SHELL

  config.vm.define "srvlog" do |srvlog|
    srvlog.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2056"]
    end
    srvlog.vm.network "public_network", ip: '192.168.1.111'
    srvlog.vm.hostname = "srvlog"
  end


  config.vm.define "web01" do |web01|
    web01.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2056"]
    end
    web01.vm.network "public_network", ip: '192.168.1.100'
    
    web01.vm.hostname = "web01"
  end

end
