MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
                },

    }

	

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "forwarded_port", guest: 8080, host: 8080
          box.vm.network "forwarded_port", guest: 8081, host: 8081
          box.vm.network "forwarded_port", guest: 8082, host: 8082

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
        	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
          end
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              setenforce 0
              yum install epel-release -y
              yum install nginx wget -y
              yum install -y php php-devel php-fpm php-cli php-mysql php-gd php-ldap php-odbc php-pdo php-pecl-memcache php-pear php-xml php-xmlrpc php-mbstring php-snmp php-soap
              cp /vagrant/www.conf /etc/php-fpm.d/www.conf
              cp /vagrant/nginx.conf /etc/nginx/nginx.conf
              wget https://ru.wordpress.org/wordpress-4.7.5-ru_RU.tar.gz
              tar -xf wordpress-4.7.5-ru_RU.tar.gz
              cp -r wordpress /var/www/html/
              curl -sL https://rpm.nodesource.com/setup_11.x | bash -
              yum install -y nodejs
              mkdir -p /var/www/html/sysmon
              cp /vagrant/server.js /var/www/html/sysmon/server.js
              npm install forever -g
              cd /var/www/html/sysmon/
              forever start server.js
              yum install install python-pip python-devel nginx gcc -y
              pip install virtualenv
              mkdir /opt/myproject
              cd /opt/myproject
              virtualenv myprojectenv
              source myprojectenv/bin/activate
              pip install uwsgi
              cp /vagrant/wsgi.py /opt/myproject/wsgi.py
              cp /vagrant/myproject.ini /opt/myproject/myproject.ini
              deactivate
              cp /vagrant/uwsgi.service /etc/systemd/system/uwsgi.service
              systemctl start uwsgi.service
              systemctl start php-fpm              
              systemctl restart nginx
    SHELL

      end
  end
end